routes/web.php
<?php

use App\Http\Controllers\CategoryController;
use App\Http\Controllers\DepartmentController;
use App\Http\Controllers\DoonarController;
use App\Http\Controllers\EmployeeController;
use App\Http\Controllers\ItemController;
use App\Http\Controllers\ItemStatusController;
use App\Http\Controllers\ItemTypeController;
use App\Http\Controllers\UnitController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\WarehouseKeeperController;
use Faker\Guesser\Name;
use GuzzleHttp\Middleware;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Route::get('/', function () {
    return view('test');
});


Route::get('/login', function () {
    return view('login'); 
});



Route::post('/login',[\App\Http\Controllers\LoginController::class, 'login'])->name('login');
Route::get('/logout',[\App\Http\Controllers\LoginController::class, 'logout'])->name('logout');
Route::resource('users', UserController::class)->middleware('auth');
//start of Employee Route
Route::get('/addEmployee',[EmployeeController::class,'create'])->name('addEmployee.create');
Route::post('/saveEmployee',[EmployeeController::class,'store'])->name('saveEmployee.store');
Route::get('/showEmployee',[EmployeeController::class,'show'])->name('showEmployee.show');
Route::get('/deleteEmployee/{id}',[EmployeeController::class,'destroy']);
Route::get('/editEmployee/{id}',[EmployeeController::class,'edit']);
Route::post('/UpdateEmployee',[EmployeeController::class,'update'])->name('UpdateEmployee.Update');
//End

//start of Item Route
Route::get('/addItem',[ItemController::class,'create'])->name('addItem.create');
Route::post('/saveItem',[ItemController::class,'store'])->name('saveItem.store');
Route::get('/showItem',[ItemController::class,'show'])->name('showItem.show');
Route::get('/deleteItem/{id}',[ItemController::class,'destroy']);
Route::get('/editItem/{id}',[ItemController::class,'edit']);
Route::post('/UpdateItem',[ItemController::class,'update'])->name('UpdateItem.Update');
//End

//item Status
Route::get('/addItemStatus',[ItemStatusController::class,'create'])->name('addItemStatus.create');
Route::post('/saveItemStatus',[ItemStatusController::class,'store'])->name('saveItemStatus.store');
Route::get('/showItemStatus',[ItemStatusController::class,'show'])->name('showItemStatus.show');
Route::get('/deleteItemStatus/{id}',[ItemStatusController::class,'destroy']);
Route::get('/editItemStatus/{id}',[ItemStatusController::class,'edit']);
Route::post('/UpdateItemStatus',[ItemStatusController::class,'update'])->name('UpdateItemStatus.Update');
//end
//start of Category
Route::get('/addCategory',[CategoryController::class,'create'])->name('addCategory.create');
Route::post('/saveCategory',[CategoryController::class,'store'])->name('saveCategory.store');
Route::get('/show',[CategoryController::class,'show'])->name('listCategory.show');
Route::get('/deleteCategory/{id}',[CategoryController::class,'destroy']);
Route::get('/editCategory/{id}',[CategoryController::class,'edit']);
Route::post('/UpdateCategory',[CategoryController::class,'update'])->name('UpdateCategory.Update');
//end of Category

//Start of Item Unit Route
Route::get('/addUnit',[UnitController::class,'create'])->name('addUnit.create');
Route::post('/saveUnit',[UnitController::class,'store'])->name('saveUnit.store');
Route::get('/showUnit',[UnitController::class,'show'])->name('showUnit.show');
Route::get('/deleteUnit/{id}',[UnitController::class,'destroy']);
Route::get('/editUnit/{id}',[UnitController::class,'edit']);
Route::post('/UpdateUnit',[UnitController::class,'update'])->name('UpdateUnit.Update');
//End

//Item Type
Route::get('/addItemType',[ItemTypeController::class,'index'])->name('itemType.add');
Route::post('/saveitemType',[ItemTypeController::class,'store'])->name('itemType.store');
Route::get('/listItemType',[ItemTypeController::class,'show'])->name('listItemType.show');
Route::get('/delete/{id}',[ItemTypeController::class,'destroy']);
Route::get('/editItemType/{id}',[ItemTypeController::class,'edit']);
Route::post('/UpdateItemType',[ItemTypeController::class,'update'])->name('ItemType.Update');
//end

//start of department route
Route::get('/addDepartment',[DepartmentController::class,'create'])->name('addDepartment.create');
Route::post('/saveDepartment',[DepartmentController::class,'store'])->name('saveDepartment.store');
Route::get('/showDepartmemt',[DepartmentController::class,'show'])->name('showDepartment.show');
Route::get('/deleteDepartment/{id}',[DepartmentController::class,'destroy']);
Route::get('/editDepartment/{id}',[DepartmentController::class,'edit']);
Route::post('/UpdateDepartment',[DepartmentController::class,'update'])->name('UpdateDepartment.Update');
//end

//start of Donor Route
Route::get('/addDonor',[DoonarController::class,'create'])->name('addDonor.create');
Route::post('/saveDonar',[DoonarController::class,'store'])->name('saveDoonar.store');
Route::get('/showDonar',[DoonarController::class,'show'])->name('showDoonar.show');
Route::get('/deleteDonar/{id}',[DoonarController::class,'destroy']);
Route::get('/editIDonor/{id}',[DoonarController::class,'edit']);
Route::post('/UpdateDonor',[DoonarController::class,'update'])->name('UpdateDonor.Update');
//end

// Warehouse keeper 
Route::get('/addWarehouseKeeper',[WarehouseKeeperController::class,'create'])->name('addWarehouseKeeper.create');
Route::post('/saveWarehouseKeeper',[WarehouseKeeperController::class,'store'])->name('saveWarehouseKeeper.store');
Route::get('showWarehouseKeepers',[WarehouseKeeperController::class,'show'])->name('showWarehouseKeepers.show');
Route::get('/deleteWarehouse/{id}',[WarehouseKeeperController::class,'destroy']);
Route::get('/editWarehousKeeper/{id}',[WarehouseKeeperController::class,'edit']);
Route::post('/UpdatWarehousKeeper',[WarehouseKeeperController::class,'update'])->name('UpdatWarehousKeeper.Update');
//end


Route::get('/404', function () {
    return view('404'); 
});

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable,HasRoles;
   
    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\User;
use Illuminate\Support\Facades\Hash;
use Spatie\Permission\Models\Role;
use Illuminate\Support\Facades\Auth;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $all = User::all();
        return view('users.index',['users' => $all]);
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $roles = Role::all();
        

        return view('users.create', compact('roles'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
  
        $user = new User;
        
        $user->username = $request->username;
        
        $user->fname = $request->fname;
        $user->lname = $request->lname;
        
        $user->email = $request->email;
        
        $user->contact_number = $request->contact_number;
        $user->posation = $request->posation;
        $user->status = "1";
        $user->password = Hash::make('Afghan@786');
        $user->save();
        
        $user->syncRoles($request['role']);
        
        return redirect()->route('users.index')->with('message', 'User added!</span> User Account '.$request->username.' have been Added');
     

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        return "show <br>".$user;
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        
        $roles = Role::all();
        $userRole = $user->roles;
        
         return view('users.edit',compact('user','roles','userRole'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        
        $user = User::find($id);
        $user->fname = $request->fname;
        $user->lname = $request->lname;
        $user->email = $request->email;
        $user->contact_number = $request->contact_number;
        $user->posation = $request->posation;
        $user->status = $request->status;
        $user->save();
        $user->syncRoles($request->role);
        
        return redirect()->route('users.index')->with('message', 'User '.$user->username.'! has been edited ');
     
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $delete_user = User::find($user->id);
        $delete_user->delete();

        return redirect()->route('users.index')->with('message', 'User Deleted!</span> User Account '.$user->username.' have been deleted');
     
    }
    public function setting()
    {
     
     $user = User::find(session('id'));
     
       return view('users.setting' ,compact('user'));
       
    }
     public function profileupdate(Request $request)
    {
        
    
        if($request->hasFile('image')) {
            $ext = $request->file('image')->getClientOriginalExtension();
            $file = session('username').'.jpg';
           
            $request->file('image')->storeAs('public/Users/',$file );
        }
        $user = User::find(session('id'));
        $user->fname = $request->fname;
        $user->lname = $request->lname;
        $user->email = $request->email;
        $user->contact_number = $request->contact_number;
        $user->posation = $request->posation;
        $user->save();
     


        return redirect()->route('setting')->with('message', 'profile Updated!</span> User Account '.$user->username.' have been Updated');
     

       # $user = User::find(session('id'));
       # return $user;
    }
}

resources/views/users/create.blade.php
@extends('layouts.app')

@section('page_title', __('general.dashboard'))
@section('title', __('general.dashboard'))



@section('body')

<div class="portlet light bordered">
    <div class="portlet-title">
        <div class="caption">
            <i class="icon-equalizer font-red-sunglo"></i>
            <span class="caption-subject font-red-sunglo bold uppercase">Adding New User</span>
            <span class="caption-helper"></span>
        </div>
    
    </div>
    <div class="portlet-body form">
        @if (Session::has('addItem'))
            <div class="alert alert-success" role="alert">
                {{Session::get('addItem')}}
            </div>
            
        @endif
        <!-- BEGIN FORM-->
        <form action="{{route('users.store')}}" method="POST" class="form-horizontal">
            @csrf
            <div class="form-body">
            <div class="form-group">
                    <label class="col-md-2 control-label">Username</label>
                    <div class="col-md-8">
                        <input  type="text" class="form-control" name="username" value="" id="item_name" placeholder="Username ">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-2 control-label">First Name</label>
                    <div class="col-md-8">
                        <input  type="text" class="form-control" name="fname" value="" id="item_name" placeholder="First Name">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-2 control-label">Last Name</label>
                    <div class="col-md-8">
                        <input  type="text" class="form-control" name="lname" value="" id="item_name" placeholder="Last Name">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-2 control-label"> Email</label>
                    <div class="col-md-8">
                        <input  type="email" class="form-control" name="email" value="" id="item_name" placeholder="Email Adress">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-2 control-label"> Contact Number</label>
                    <div class="col-md-8">
                        <input  type="text" class="form-control" name="contact_number" value="" id="item_name" placeholder="Contact Number ">
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-md-2 control-label"> Posation</label>
                    <div class="col-md-8">
                        <input  type="text" class="form-control" name="posation" value="" id="item_name" placeholder="Enter Item Name ">
                    </div>
                </div>
    

                <div class="form-group">
                    <label class="col-md-2 control-label" for="form_control_1">Roles</label>
                    <div class="col-md-8">
                        <select class="form-control" id="form_control_1" name="role">
                        @foreach ($roles as $role)
                                    <option value="{{$role->id}}">{{$role->name}}</option> 
                                    @endforeach
                        </select>
                        <div class="form-control-focus"> </div>
                    </div>
                </div>
           

            </div>
            <div class="form-actions">
                <div class="row">
                    <div class="col-md-offset-3 col-md-4">
                        <button type="submit" class="btn green">Submit</button>
                        <button type="reset" class="btn default">Cancel</button>
                    </div>
                </div>
            </div>
        </form>
        <!-- END FORM-->
    </div>
</div>      
@endsection

resources/views/users/edit.blade.php
@extends('layouts.app')

@section('page_title', __('general.dashboard'))
@section('title', __('general.dashboard'))



@section('body')

     
@endsection

resources/views/users/index.blade.php
@extends('layouts.app')

@section('page_title', __('general.dashboard'))
@section('title', __('general.dashboard'))

@section('body')

      <!-- END PAGE HEADER-->
    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN EXAMPLE TABLE PORTLET-->
            <div class="portlet light bordered">
                <div class="portlet-title">
                    <div class="caption font-dark">
                        <span class="caption-subject bold uppercase">List of Units</span>
                    </div>
                    <div class="tools">
                        <div class="portlet-title">
                            <div class="actions">
                                <div class="btn-group">
                                    <a class="btn red btn-outline btn-circle" href="javascript:;" data-toggle="dropdown">
                                        <i class="fa fa-share"></i>
                                        <span class="hidden-xs"> Tools </span>
                                        <i class="fa fa-angle-down"></i>
                                    </a>
                                    <ul class="dropdown-menu pull-right" id="sample_3_tools">
                                        <li>
                                            <a href="javascript:;" data-action="0" class="tool-action">
                                                <i class="icon-printer"></i> Print</a>
                                        </li>
                
                                        <li>
                                            <a href="javascript:;" data-action="2" class="tool-action">
                                                <i class="icon-doc"></i> PDF</a>
                                        </li>
                                        <li>
                                            <a href="javascript:;" data-action="3" class="tool-action">
                                                <i class="icon-paper-clip"></i> Excel</a>
                                        </li>
                                        <li>
                                            <a href="javascript:;" data-action="4" class="tool-action">
                                                <i class="icon-cloud-upload"></i> CSV</a>
                                        </li>
                                        
                                    </ul>
                                </div>
                            </div>
                        </div>    
                    </div>
                </div>
                <div class="portlet-body">
                    @if (Session::has('delete_unit'))
                        <div class="alert alert-danger" role="alert">
                            {{Session::get('delete_unit')}}
                        </div>
                        
                    @endif
                    <table class="table table-striped table-bordered table-hover" id="sample_1">
                        <thead>
                            <tr>
                              
                            <th>  {{__('general.Username')}}</th>
                        <th>  {{__('general.email')}} </th>
                        <th>  {{__('general.role_mng')}}</th>
                        <th>  {{__('general.Status')}}</th>
                        <th>  {{__('general.Position')}}</th>
                        <th>  {{__('general.action')}}</th>

                            </tr>
                        </thead>
                  
                        <tbody>
                            @foreach ($users as $user )
                            <tr>
                             
                            <td>{{$user->username;}}</td>
                        <td><a href="#">{{$user->email;}}</a></td>
                        <td>  @foreach($user->getRoleNames() as $role)
                            {{ $role }}
                          @endforeach</td>
                        <td>@if ($user->status == 1)
                            <span class="badge badge-success">Active</span>
                       
                                
                            @else
                            <span class="badge badge-success bg-danger">inActive</span>  
                            @endif
                        </td>
                        <td>{{$user->posation;}}</td>
                                <td>
                            <div class="list-icons">
                              
                            <a class="btn btn-info" href="{{ route('users.edit', $user->id)}}" class="list-icons-item text-primary-600" style="margin-right:10px;">edit</i></a>
                              
                        
    
                                <form id="delete{{$user->id}}" action="{{ route('users.destroy', $user->id)}}" method="post">
                                    <button style="float:left" class="btn btn-danger">delete</button>
                                  @csrf
                                  @method('DELETE')
                                </form>
                            </div>
                        </td>
                               <td>

                               </td>
                            </tr>
                            @endforeach
                            
                                         
                          </tbody>
                    </table>
                </div>
            </div>  
            
            
            <!-- END CORE PLUGINS -->
            <!-- BEGIN PAGE LEVEL PLUGINS -->
            <script src="../assets/global/scripts/datatable.js" type="text/javascript"></script>
            <script src="../assets/global/plugins/datatables/datatables.min.js" type="text/javascript"></script>
            <!-- END PAGE LEVEL PLUGINS -->
            <!-- BEGIN THEME GLOBAL SCRIPTS -->
            <!-- END THEME GLOBAL SCRIPTS -->
            <!-- BEGIN PAGE LEVEL SCRIPTS -->
            <script src="../assets/pages/scripts/table-datatables-buttons.min.js" type="text/javascript"></script>
            <!-- END PAGE LEVEL SCRIPTS -->
            <!-- BEGIN THEME LAYOUT SCRIPTS -->
            <!-- END THEME LAYOUT SCRIPTS -->
        <!-- Google Tag Manager -->
    <noscript><iframe src="http://www.googletagmanager.com/ns.html?id=GTM-NGFVTN"
    height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    '../../../../../www.googletagmanager.com/gtm5445.html?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-NGFVTN');</script>   
@endsection

resources/views/users/setting.blade.php
@extends('Layout.index')


@section('content')
<!-- Content area -->


<div class="content d-flex justify-content-center align-items-center">
   

    <!-- Registration form -->
    <form action="{{route('profileupdate')}}" class="flex-fill" method="POST" enctype="multipart/form-data">
        @csrf
        <div class="row">
            <div class="col-lg-12">
               
                <div class="card mb-0">
                    {{$user->id}}
                    <div class="card-body">
                        <div class="text-center mb-3">
                            <i class="icon-plus3 icon-2x text-success border-success border-3 rounded-round p-3 mb-3 mt-1"></i>
                            <h5 class="mb-0">Create account</h5>
                            <span class="d-block text-muted">All fields are required</span>
                        </div>

                        <div class="form-group form-group-feedback form-group-feedback-right">
                            <input type="text" class="form-control" placeholder="Choose username" name="username" value="{{$user->username}}" disabled>
                            <div class="form-control-feedback">
                                <i class="icon-user-plus text-muted"></i>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group form-group-feedback form-group-feedback-right">
                                    <input type="text" class="form-control" placeholder="First name" name="fname" value="{{$user->fname}}">
                                    <div class="form-control-feedback">
                                        <i class="icon-user-check text-muted"></i>
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group form-group-feedback form-group-feedback-right">
                                    <input type="text" class="form-control" placeholder="Second name" name="lname" value="{{$user->lname}}">
                                    <div class="form-control-feedback">
                                        <i class="icon-user-check text-muted"></i>
                                    </div>
                                </div>
                            </div>
                        </div>

                      

                        <div class="row">
                            <div class="col-md-6">
                                <div class="form-group form-group-feedback form-group-feedback-right">
                                    <input type="email" class="form-control" placeholder="Your email" name="email" value="{{$user->email}}">
                                    <div class="form-control-feedback">
                                        <i class="icon-mention text-muted"></i>
                                    </div>
                                </div>
                            </div>

                            <div class="col-md-6">
                                <div class="form-group form-group-feedback form-group-feedback-right">
                                    <div class="input-group">
                                        <span class="input-group-prepend">
                                            <span class="input-group-text">+93</span>
                                        </span>
                                        <input type="text" class="form-control" placeholder="Contact Number" name="contact_number" value="{{$user->contact_number}}">
                                    </div>
                                
                                    
                                    <div class="form-control-feedback">
                                        <i class="icon-phone2 text-muted"></i>
                                    </div>
                                    
                                </div>
                                
                            </div>
                            
                        </div>
                        <div class="form-group form-group-feedback form-group-feedback-right">
                            <input type="text" class="form-control" placeholder="job title/posation" name="posation" value="{{$user->posation}}">
                            <div class="form-control-feedback">
                                <i class="icon-user-plus text-muted"></i>
                            </div>
                        </div>
                        
                        <div class="form-group row">
                            <label class="col-lg-2 col-form-label font-weight-semibold">Single file upload:</label>
                            <div class="col-lg-10">
                                <input type="file" class="file-input form-control-lg" name="image" data-show-caption="false" data-show-upload="false" data-browse-class="btn btn-primary btn-lg" data-remove-class="btn btn-light btn-lg" data-fouc>
										
                                <span class="form-text text-muted">Uploaded pic will be shown here.</span>
                            </div>
                        </div>
                     

                        <button type="submit" class="btn bg-teal-400 btn-labeled btn-labeled-right"><b><i class="icon-plus3"></i></b> Update Settings </button>
                    </div>
                </div>
            </div>
        </div>
    </form>
    <!-- /registration form -->

</div>
<!-- /content area -->

@endsection